language: generic
sudo: required

services:
  - docker

- before_install:
  - docker build -t jay/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jay/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-159625583966"
  bucket_path: "docker-react"
  on:
    branch: "master"
  access_key_id: "$AWS_SECRET_KEY"
  secret_access_key:
    secret: "$AWS_SECRET_KEY"
    
